Repository BrunoBuona/my-tinerary-la-pandita, pull requests merged in 2022-11, with the labels that each got.

#35 Fix mt f2 08
  src/components/LoginForm/LoginForm.jsx
Labels: enhancement

#51 [FIX-MT-F2-14]
  src/components/NewHotel/NewHotel.css
  src/components/NewHotel/NewHotel.jsx
Labels: Completed

#52 [FIX-MT-F2-10]
  src/components/HotelsPage/Hotels.jsx
Labels: Completed

#55 [MT-F2-12] Details
  src/App.js
  src/components/DetailsHotel/DetailsHotels.css
  src/components/DetailsHotel/DetailsHotels.jsx
  src/components/DetailsHotel/Show.jsx
  src/components/HotelsPage/HotelPrinter.jsx
  src/data/show.js
Labels: Completed

#61 [MT-02-23]
  src/api/url.js
  src/components/NewHotel/NewHotel.jsx
Labels: Completed

#62 [MT-02-24]
  src/components/HotelsPage/HotelPrinter.jsx
  src/components/HotelsPage/Hotels.jsx
Labels: Completed

#63 MT-01-19
  src/components/Cities/Cities.css
  src/components/Cities/Cities.jsx
  src/components/Cities/CitiesPrinter.jsx
  src/components/inputSearch/InputSeach.jsx
Labels: bug

#68 FIX-SPRINT-2-MT-26-02
  src/components/DetailsHotel/DetailsHotels.css
  src/components/DetailsHotel/DetailsHotels.jsx
  src/components/DetailsHotel/Show.jsx
  src/components/HotelsPage/Hotels.jsx
  src/index.js
Labels: Completed

#69 [MT-02-38]
  .gitignore
  package-lock.json
  package.json
  src/App.js
  src/api/url.js
  src/components/Cities/Cities.jsx
  src/components/Cities/CitiesPrinter.jsx
  src/components/CitiesPrinter/CitiesPrinter.jsx
  src/components/DetailsCities/DitailsCities.jsx
  src/components/DetailsHotel/DetailsHotels.css
  src/components/DetailsHotel/DetailsHotels.jsx
  src/components/DetailsHotel/Show.jsx
  src/components/Header/Header.css
  src/components/Header/Header.jsx
  src/components/Home2/Carrousel/Carrousel.css
  src/components/Home2/Carrousel/Carrousel.jsx
  src/components/Home2/Carrousel/ImagesC.jsx
  src/components/Home2/Carrousel/Slideshow.jsx
  src/components/Home2/Carrousel/Thumbnail.jsx
  src/components/Hotels/Hotels.css
  src/components/Hotels/Hotels.jsx
  src/components/HotelsPage/HotelPrinter.jsx
  src/components/HotelsPage/Hotels.jsx
  src/components/LoginForm/LoginForm.css
  src/components/LoginForm/LoginForm.jsx
  src/components/NewHotel/NewHotel.jsx
  src/components/checkbox/Checkbox.jsx
  src/components/home1/CallToAction/CallToAction.jsx
  src/components/home1/Home1.jsx
  src/components/home1/Navbar/NavBar.css
  src/components/home1/Navbar/NavBar.jsx
  src/components/home1/Navbar/NavBar2.jsx
  src/components/inputSearch/InputSeach.jsx
  src/index.js
  src/layouts/Footer/Footer.css
  src/layouts/Footer/FooterNav/FooterNav.jsx
  src/layouts/Main.jsx
  src/pages/Cities/Cities.css
  src/pages/Cities/Cities.jsx
  src/pages/DetailsCities/DitailsCities.css
  src/pages/DetailsCities/DitailsCities.jsx
  src/pages/HomePage/Home.jsx
  src/pages/NewCity/NewCity.css
  src/pages/NewCity/NewCity.jsx
  src/redux/actions/hotelAction.js
  src/redux/reducers/hotelReducer.js
  src/redux/reducers/rootReducer.js
Labels: Completed

#70 MT-02-40
  package-lock.json
  package.json
  src/components/NewHotel/NewHotel.jsx
  src/redux/actions/hotelAction.js
Labels: Completed

#74 [MT-02-44]
  src/App.js
  src/components/MyShows/EditShowCard.css
  src/components/MyShows/EditShowCard.jsx
  src/components/MyShows/ShowCards.jsx
  src/components/MyShows/Shows.css
  src/pages/myShows/myShows.css
  src/pages/myShows/myShows.jsx
  src/redux/actions/myShowAction.js
  src/redux/reducers/myShowReducer.js
  src/redux/reducers/rootReducer.js
Labels: Completed

#79 [MT-02-46]
  package-lock.json
  package.json
  src/components/LoginForm/LoginForm.jsx
  src/index.js
  src/redux/actions/loginForm.js
  src/redux/reducers/loginReducer.js
  src/redux/reducers/rootReducer.js
Labels: Completed

#80 MT-01-47
  src/App.js
  src/components/Header/Header.jsx
  src/components/ProtectedRoute/ProtectedRoute.js
  src/components/home1/Navbar/NavBar.css
  src/components/home1/Navbar/NavBar2.jsx
Labels: Completed

#81 [MT-02-48]
  src/App.js
  src/components/Header/Header.jsx
  src/components/LoginForm/LoginForm.jsx
  src/components/home1/Navbar/NavBar.jsx
Labels: Completed

#82 [MT-02-50]
  src/App.js
  src/components/Header/Header.jsx
  src/components/Profile/ViewProfile1.jsx
  src/components/Profile/ViewProfile2.jsx
  src/components/Profile/components/EditProfile.jsx
  src/components/Profile/components/SeeProfile.jsx
  src/components/Profile/styles/ViewProfile1.css
  src/components/Profile/styles/ViewProfile2.css
  src/components/home1/Navbar/NavBar.css
  src/components/home1/Navbar/NavBar.jsx
Labels: Completed

#83 [FIX-MT-02-50]
  src/components/Profile/components/EditProfile.jsx
  src/components/Profile/styles/ViewProfile1.css
  src/components/Profile/styles/ViewProfile2.css
Labels: Completed

#85 [FIX-MT-02-52]
  src/App.js
  src/components/Header/Header.jsx
  src/components/MyShows/ShowCards.jsx
  src/components/MyShows/Shows.css
  src/components/NewShow/NewShow.css
  src/components/NewShow/NewShow.jsx
  src/components/home1/Navbar/NavBar2.jsx
  src/pages/myShows/myShows.css
  src/pages/myShows/myShows.jsx
Labels: Completed

#86 [MT-02-54]
  src/pages/myHotels/myHotels.jsx
Labels: Completed

#89 [FIX-sprint 4]
  src/components/MyHotels/EditCard.jsx
  src/components/MyShows/EditShowCard.jsx
  src/redux/actions/myHotelAction.js
  src/redux/actions/myShowAction.js
Labels: Completed

#90 [FIX-SPRINT-4]
  src/components/MyHotels/Cards.jsx
  src/components/MyShows/EditShowCard.jsx
  src/components/MyShows/ShowCards.jsx
  src/components/NewHotel/NewHotel.jsx
  src/components/NewShow/NewShow.jsx
  src/pages/myHotels/myHotels.jsx
  src/pages/myShows/myShows.jsx
Labels: Completed

#95 Delete README.old.md
  README.old.md
Labels: documentation, Completed
